server:
  port: 2220

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    org.springframework.security: INFO

spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://172.19.56.127:3306/cfh_activity?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: cfh_activity
    password: Cfh_activity123

mybatis:
  configuration:
    map-underscore-to-camel-case: true   #开启驼峰命名转换
